// <auto-generated />
namespace BIFastWebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddbankMaster : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddbankMaster));
        
        string IMigrationMetadata.Id
        {
            get { return "202204220856178_AddbankMaster"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
